+bump damsel with yandex payment tool
rbkmoney/wapi_pcidss_v0 pull request #52
Opened 2020-12-07 16:46 UTC by dinama

2020-12-07 16:49 UTC, kpy3 requested changes
Обновление релиза лучше отдельно, не надо всё в кучу

2020-12-07 16:54 UTC, dinama commented
> Обновление релиза лучше отдельно, не надо всё в кучу

ты про то что я убрал из корня relx? но ведь на результат это не влияет. новых опций не добавилось.

2020-12-07 17:01 UTC, dinama commented
убрал очищение конфига от мусора

2020-12-07 21:57 UTC, artbrunov submitted a review, later dismissed

2020-12-08 20:21 UTC, artbrunov approved these changes

2020-12-09 09:42 UTC, kpy3 approved these changes

2020-12-09 09:44 UTC, merged